### ISSUE TITLE
1.4.4: segfault in Gnome with Wayland

### ISSUE THREAD

**Issue by onlyjob** [CristianHenzel/ClipIt#96]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903149#25
Clipit built with appindicator and GTK-3 segfaults as follows in Debian "unstable":

~~~~
(gdb) bt
#0  0x00007ffff6514339 in XGetModifierMapping () at /usr/lib/x86_64-linux-gnu/libX11.so.6
#1  0x000055555556389a in reload_modmap (modmap=0x5555556142c0, keymap=0x55555559ed80) at eggaccelerators.c:549
#2  0x000055555556389a in egg_keymap_get_modmap (keymap=0x55555559ed80) at eggaccelerators.c:646
#3  0x0000555555563ae0 in egg_keymap_resolve_virtual_modifiers (keymap=0x55555559ed80, virtual_mods=EGG_VIRTUAL_LOCK_MASK, concrete_mods=0x555555569114 <caps_lock_mask>) at eggaccelerators.c:475
#4  0x000055555555e245 in lookup_ignorable_modifiers (keymap=0x55555559ed80) at keybinder.c:54
#5  0x000055555555e61e in keybinder_init () at keybinder.c:242
#6  0x000055555555b34a in clipit_init () at main.c:972
#7  0x000055555555b34a in main (argc=<optimized out>, argv=<optimized out>) at main.c:1046
~~~~

**Comment by kabo** [comment]
v1.4.2-1.2 works fine

**Comment by kabo** [comment]
@hista You can download 1.4.2-1.2 [here](http://snapshot.debian.org/package/clipit/1.4.2-1.2/).

```sh
sudo dpkg -i clipit_1.4.2-1.2_*.deb
sudo apt-mark hold clipit
```

**Comment by onlyjob** [comment]
I wouldn't recommend downgrade as 1.4.2 is too old (built in 2013; minor update in 2016) and it is not properly re-built with updated libraries...

Personally I've switched to _parcellite_ and _xfce4-clipman_ - worthy well maintained alternatives that work very well and stable.

**Comment by andrewshadura** [comment]
According to [rickyrockrat/parcellite](https://github.com/rickyrockrat/parcellite/commits/master), Parcellite hasn’t seen any meaningful updates since 2014, and of course nobody ported 2c7c9d6 there…
